name: PR Validation

on:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: "Deps: show dependencies metadata"
        uses: lirantal/github-action-new-dependencies-advisor@06912df98836c8698a9e7525795612b439ff7612
        if: github.event_name == 'pull_request'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn
      - run: yarn lint:lockfile
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
      - run: yarn e2e
      - run: yarn build

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false

  kics:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Kics
        uses: checkmarx/kics-github-action@master
        with:
          path: Dockerfile
          output_path: kics-results
          output_formats: json,sarif
          enable_comments: ${{ github.event_name == 'pull_request'}}
          fail_on: high,medium
      - name: Show KICS results
        if: failure()
        run: cat kics-results/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: kics-results/results.sarif
